<h3>Your logo</h3>
<table class="form-table">
<tr valign="top">
    <th scope="row"><label >Image:</label></th>
    <td colspan="3">
        <input type="url" size="36" name="one-logo[image]" value="<?= $this->settings['one-logo']['image'] ?>" class="regular-text" />
        <input type="button" value="Upload Image" class="image-upload button-secondary" />
        <br />
        <span class="description">If empty, we'll show the blog title.</span>
    </td>
</tr>

<tr valign="top">
    <th scope="row"><label>Advanced options:</label></th>
    <td width="110px">
        <input type="text" name="one-logo[color]" value="<?= $this->settings['one-logo']['color'] ?>" class="color-field" />
        <br />
        <span class="description">background color</span>
    </td>
    
    <td width="145px">
        <input type="text" name="one-logo[padding]" value="<?= $this->settings['one-logo']['padding'] ?>" />
        <br />
        <span class="description">padding <small>(css value)</small></span>
    </td>
    
    <td>
        <label><input type="checkbox" name="one-header[fixed]" value="true" <?php echo ($this->settings['one-header']['fixed'] == true) ? 'checked="checked" ': ''; ?>/>
        <span class="description">fixed header</span></label>
    </td>
</tr>
</table>

<br />

<h3>Colors</h3>
<table class="form-table">
<tr valign="top">
    <th scope="row"><label >Elements:</label></th>
    <td width="110px">
        <input type="text" name="one-colors[primary]" value="<?= $this->settings['one-colors']['primary'] ?>" class="color-field" />
        <br />
        <span class="description">primary color</span>
    </td>
    
    <td>
        <input type="text" name="one-colors[secondary]" value="<?= $this->settings['one-colors']['secondary'] ?>" class="color-field" />
        <br />
        <span class="description">secondary color</span>
    </td>
</tr>
</table>

<table class="form-table">
<tr valign="top">
    <th scope="row"><label >Links:</label></th>
    <td width="110px">
        <input type="text" name="one-colors[link]" value="<?= $this->settings['one-colors']['link'] ?>" class="color-field" />
        <br />
        <span class="description">normal</span>
    </td>
    <td width="110px">
        <input type="text" name="one-colors[link-h]" value="<?= $this->settings['one-colors']['link-h'] ?>" class="color-field" />
        <br />
        <span class="description">:hover</span>
    </td>
    <td width="110px">
        <input type="text" name="one-colors[link-a]" value="<?= $this->settings['one-colors']['link-a'] ?>" class="color-field" />
        <br />
        <span class="description">:active</span>
    </td>
    <td>
        <input type="text" name="one-colors[link-vv]" value="<?= $this->settings['one-colors']['link-v'] ?>" class="color-field" />
        <br />
        <span class="description">:visited</span>
    </td>
</tr>
</table>